package net.nikosnook.core;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import java.nio.file.Path;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
class NativeWithdrawalTest {
 @TempDir Path dir;NookStore store;UUID owner=UUID.randomUUID(),co=UUID.randomUUID(),buyer=UUID.randomUUID();NativeShop.Offer offer;
 @BeforeEach void setup()throws Exception {store=new NookStore(dir.resolve("db"));for(UUID id:List.of(owner,co,buyer))store.join(id,id.toString(),0,10000);store.definePlot("one",3000);store.rent("one",owner,0);offer=store.createNativeOffer("one",owner,new byte[]{1},4,100,1);store.creditNativeStock(UUID.randomUUID(),offer.id(),owner,12,2);}
 @AfterEach void close()throws Exception{store.close();}
 @Test void chosenWithdrawalLeavesOfferOpenAndDoesNotChangeMoney()throws Exception {long before=store.account(owner).orElseThrow().cents();var receipt=store.reserveNativeStockWithdrawal(UUID.randomUUID(),offer.id(),owner,3,3);assertEquals(3,receipt.quantity());assertEquals(0,receipt.cents());assertEquals(9,store.nativeOffer(offer.id()).stock());assertFalse(store.nativeOffer(offer.id()).closed());assertEquals(before,store.account(owner).orElseThrow().cents());store.settleNativePurchase(UUID.randomUUID(),offer.id(),buyer,1,4);assertEquals(5,store.nativeOffer(offer.id()).stock());}
 @Test void restartAndRetryCannotReserveStockTwice()throws Exception {UUID id=UUID.randomUUID();store.reserveNativeStockWithdrawal(id,offer.id(),owner,3,3);store.close();store=new NookStore(dir.resolve("db"));store.reserveNativeStockWithdrawal(id,offer.id(),owner,3,4);assertEquals(9,store.nativeOffer(offer.id()).stock());assertEquals("PENDING",store.nativeDeliveryState(id));assertThrows(IllegalArgumentException.class,()->store.reserveNativeStockWithdrawal(id,offer.id(),owner,4,5));}
 @Test void stockMemberMayWithdrawButBuildOnlyAndOutsiderCannot()throws Exception {var invitation=store.invite("one",owner,co,"STOCK",2);store.acceptInvitation(invitation.token(),co,2);store.reserveNativeStockWithdrawal(UUID.randomUUID(),offer.id(),co,3,3);store.changeRole("one",owner,co,"BUILD",4);assertThrows(IllegalArgumentException.class,()->store.reserveNativeStockWithdrawal(UUID.randomUUID(),offer.id(),co,3,5));assertThrows(IllegalArgumentException.class,()->store.reserveNativeStockWithdrawal(UUID.randomUUID(),offer.id(),buyer,3,5));assertEquals(9,store.nativeOffer(offer.id()).stock());}
 @Test void invalidAmountAndInsufficientStockDoNotReserveAnything()throws Exception {for(int count:new int[]{0,-1,13,65})assertThrows(IllegalArgumentException.class,()->store.reserveNativeStockWithdrawal(UUID.randomUUID(),offer.id(),owner,count,3));assertEquals(12,store.nativeOffer(offer.id()).stock());assertTrue(store.nativeDeliveries(owner).isEmpty());}
 @Test void expiredOrClosedOfferUsesExistingOwnerRecoveryInstead()throws Exception {assertThrows(IllegalArgumentException.class,()->store.reserveNativeStockWithdrawal(UUID.randomUUID(),offer.id(),owner,3,NookStore.WEEK));store.closeNativeOffer(offer.id(),owner);assertThrows(IllegalArgumentException.class,()->store.reserveNativeStockWithdrawal(UUID.randomUUID(),offer.id(),owner,3,3));assertEquals(3,store.reserveNativeStockReturn(UUID.randomUUID(),offer.id(),owner,3,4).quantity());}
 @Test void receiptWriteFailureRollsBackStock()throws Exception {try(var c=java.sql.DriverManager.getConnection("jdbc:sqlite:"+dir.resolve("db"));var s=c.createStatement()){s.execute("CREATE TRIGGER fail_withdraw BEFORE INSERT ON native_trade_receipts BEGIN SELECT RAISE(ABORT,'injected'); END");}assertThrows(java.sql.SQLException.class,()->store.reserveNativeStockWithdrawal(UUID.randomUUID(),offer.id(),owner,3,3));assertEquals(12,store.nativeOffer(offer.id()).stock());assertTrue(store.nativeDeliveries(owner).isEmpty());}
}
