package net.nikosnook.core;
import org.junit.jupiter.api.Test;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
class NativeInventoryPlanTest {
    NativeInventoryPlan.Stack stack(String key,int amount,int limit){return new NativeInventoryPlan.Stack(key,amount,limit);}
    @Test void depositsOnlyExactMetadataAcrossStorageSlots(){var slots=Arrays.asList(stack("diamond:plain",2,64),stack("diamond:named",8,64),stack("diamond:plain",4,64),null);var plan=NativeInventoryPlan.deposit(slots,"diamond:plain",5);assertNull(plan.after().get(0));assertEquals(8,plan.after().get(1).count());assertEquals(1,plan.after().get(2).count());assertEquals(2,slots.get(0).count());}
    @Test void insufficientStockNeverChangesOriginalInventory(){var slots=new ArrayList<>(List.of(stack("coal",3,64)));assertThrows(IllegalArgumentException.class,()->NativeInventoryPlan.deposit(slots,"coal",4));assertEquals(3,slots.getFirst().count());assertThrows(IllegalArgumentException.class,()->NativeInventoryPlan.deposit(slots,"diamond",1));}
    @Test void deliveryFillsPartialStacksBeforeEmptySlots(){var slots=Arrays.asList(null,stack("stone",62,64),stack("dirt",64,64),null);var plan=NativeInventoryPlan.deliver(slots,stack("stone",1,64),5);assertEquals(64,plan.after().get(1).count());assertEquals(3,plan.after().get(0).count());assertEquals("dirt",plan.after().get(2).key());assertNull(slots.get(0));}
    @Test void unstackableBundlesNeedOneSlotPerItem(){var slots=Arrays.<NativeInventoryPlan.Stack>asList(null,null);var item=stack("sword:enchanted",1,1);var plan=NativeInventoryPlan.deliver(slots,item,2);assertEquals(1,plan.after().get(0).count());assertEquals(1,plan.after().get(1).count());assertThrows(IllegalArgumentException.class,()->NativeInventoryPlan.deliver(slots,item,3));}
    @Test void fullInventoryDoesNotPartiallyDeliver(){var slots=List.of(stack("stone",63,64));assertThrows(IllegalArgumentException.class,()->NativeInventoryPlan.deliver(slots,stack("stone",1,64),2));assertEquals(63,slots.getFirst().count());}
    @Test void plansAreImmutableAndHashesIncludeSlotOrderAndMetadata(){var slots=new ArrayList<>(Arrays.asList(stack("fish:name-A",1,64),null));var plan=NativeInventoryPlan.deposit(slots,"fish:name-A",1);byte[] before=plan.beforeHash();slots.clear();assertEquals(2,plan.before().size());assertThrows(UnsupportedOperationException.class,()->plan.after().set(0,null));assertArrayEquals(before,plan.beforeHash());assertFalse(Arrays.equals(before,NativeInventoryPlan.hash(Arrays.asList(null,stack("fish:name-A",1,64)))));assertFalse(Arrays.equals(before,NativeInventoryPlan.hash(Arrays.asList(stack("fish:name-B",1,64),null))));}
    @Test void recoveryObservationNeverTreatsDifferentInventoryAsApplied(){var slots=Arrays.asList(stack("coal",3,64),null);var plan=NativeInventoryPlan.deposit(slots,"coal",2);assertEquals(NativeInventoryPlan.Observation.NOT_APPLIED,NativeInventoryPlan.observe(plan,slots));assertEquals(NativeInventoryPlan.Observation.APPLIED,NativeInventoryPlan.observe(plan,plan.after()));assertEquals(NativeInventoryPlan.Observation.AMBIGUOUS,NativeInventoryPlan.observe(plan,Arrays.asList(stack("coal",2,64),null)));}
    @Test void invalidCountsAndInconsistentItemLimitsAreRejected(){for(int count:new int[]{0,-1,65})assertThrows(IllegalArgumentException.class,()->NativeInventoryPlan.deposit(List.of(stack("coal",64,64)),"coal",count));assertThrows(IllegalArgumentException.class,()->NativeInventoryPlan.deliver(List.of(stack("key",1,16)),stack("key",1,64),1));}
}
